### ISSUE TITLE
Publish Diane in Maven

### ISSUE THREAD

**Issue by brayanjuls** [brayanjuls/diane#10]
Follow this step in order to publish this library:
* Create a sonatype account.
* Create a Jira ticket in sonatype to claim your groupId for this project.
  * Ideally the groupId should be **com.brayanjules**
* Use the plugin **sbt-pgp** to sign your artifact before publication.
* Use the plugin **sbt-sonatype** to publish to maven central.
* Use the pugin **sbt-release** to automate the release process.

**Comment by brayanjuls** [comment]
@MrPowers -  I am thinking of publishing diane to maven. I would like to do something similar to what you did in spark-daria, the only thing that I want to do differently is all the release steps I would try to automate it using the plugin sbt-release. What are your thoughts on this?

**Comment by MrPowers** [comment]
@brayanjuls - sounds like a great idea!  Automating it is definitely the best!

**Comment by brayanjuls** [comment]
[Here](https://repo1.maven.org/maven2/com/brayanjules/diane_2.12/ ) is the library published to maven, I will now try to publish it to scala version 2.13 as well. Closing this one.
